# docker-compose.yml

version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  proccess-service:
    build:
      context: ./proccess-image-service
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  logger-service:
    build:
      context: ./logger-service
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3.13-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork

  gateway:
    build:
      context: ./gateway
    ports:
      - "80:80"
    depends_on:
      - user-service
      - proccess-service
      - logger-service
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge